// <auto-generated />
using System;
using AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250406131651_initial_migration")]
    partial class initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAvailble")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Main St, New York, NY",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1001),
                            Email = "chetanmundlesd@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chetan Mundle",
                            Password = "Pass@123",
                            PhoneNumber = "9867598658",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Elm St, Los Angeles, CA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1014),
                            Email = "alice.brown@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Alice Brown",
                            Password = "Pass@123",
                            PhoneNumber = "5698758966",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 Pine Ave, Chicago, IL",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1016),
                            Email = "michael.smith@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Michael Smith",
                            Password = "Pass@123",
                            PhoneNumber = "1236589685",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "321 Oak St, Houston, TX",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1017),
                            Email = "emma.davis@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emma Davis",
                            Password = "Pass@123",
                            PhoneNumber = "4589675896",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "654 Maple Rd, Phoenix, AZ",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1019),
                            Email = "robert.wilson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Robert Wilson",
                            Password = "Pass@123",
                            PhoneNumber = "1254698759",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 6,
                            Address = "987 Birch Blvd, Philadelphia, PA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1090),
                            Email = "sophia.miller@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sophia Miller",
                            Password = "Pass@123",
                            PhoneNumber = "1236589685",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 7,
                            Address = "246 Cedar St, San Antonio, TX",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1091),
                            Email = "william.johnson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "William Johnson",
                            Password = "Pass@123",
                            PhoneNumber = "1235698759",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 8,
                            Address = "135 Spruce Dr, San Diego, CA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1093),
                            Email = "olivia.martinez@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Olivia Martinez",
                            Password = "Pass@123",
                            PhoneNumber = "9658974589",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 9,
                            Address = "753 Aspen Way, Dallas, TX",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1094),
                            Email = "james.anderson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "James Anderson",
                            Password = "Pass@123",
                            PhoneNumber = "758965874",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 10,
                            Address = "852 Redwood Ct, San Jose, CA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1097),
                            Email = "isabella.thompson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Isabella Thompson",
                            Password = "Pass@123",
                            PhoneNumber = "3652896589",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 11,
                            Address = "101 Lakeview Dr, Miami, FL",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1098),
                            Email = "chetanmundled@gmail.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Liam Carter",
                            Password = "Pass@123",
                            PhoneNumber = "7896541201",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 12,
                            Address = "202 River Rd, Denver, CO",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1100),
                            Email = "emma.foster@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Emma Foster",
                            Password = "Pass@123",
                            PhoneNumber = "7896541202",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 13,
                            Address = "303 Sunset Blvd, Seattle, WA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1102),
                            Email = "noah.brooks@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Noah Brooks",
                            Password = "Pass@123",
                            PhoneNumber = "7896541203",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 14,
                            Address = "404 Bay St, Tampa, FL",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1103),
                            Email = "ava.morgan@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Ava Morgan",
                            Password = "Pass@123",
                            PhoneNumber = "7896541204",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 15,
                            Address = "505 Palm Ave, Orlando, FL",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1105),
                            Email = "elijah.reed@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Elijah Reed",
                            Password = "Pass@123",
                            PhoneNumber = "7896541205",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 16,
                            Address = "606 Cedar Dr, Austin, TX",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1107),
                            Email = "sophia.rivera@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Sophia Rivera",
                            Password = "Pass@123",
                            PhoneNumber = "7896541206",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 17,
                            Address = "707 Birch Ln, Portland, OR",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1108),
                            Email = "lucas.gray@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Lucas Gray",
                            Password = "Pass@123",
                            PhoneNumber = "7896541207",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 18,
                            Address = "808 Spruce St, Nashville, TN",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1111),
                            Email = "mia.scott@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Mia Scott",
                            Password = "Pass@123",
                            PhoneNumber = "7896541208",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 19,
                            Address = "909 Maple Ave, Boston, MA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1112),
                            Email = "oliver.hill@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Oliver Hill",
                            Password = "Pass@123",
                            PhoneNumber = "7896541209",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 20,
                            Address = "111 Willow Way, Charlotte, NC",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1114),
                            Email = "isabella.green@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Isabella Green",
                            Password = "Pass@123",
                            PhoneNumber = "7896541210",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 21,
                            Address = "1212 Aspen St, Raleigh, NC",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1115),
                            Email = "james.adams@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "James Adams",
                            Password = "Pass@123",
                            PhoneNumber = "7896541211",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 22,
                            Address = "1313 Hickory Ln, Columbus, OH",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1117),
                            Email = "charlotte.perez@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Charlotte Perez",
                            Password = "Pass@123",
                            PhoneNumber = "7896541212",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 23,
                            Address = "1414 Sycamore Rd, Atlanta, GA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1119),
                            Email = "henry.turner@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Henry Turner",
                            Password = "Pass@123",
                            PhoneNumber = "7896541213",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 24,
                            Address = "1515 Magnolia Ct, Richmond, VA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1120),
                            Email = "amelia.torres@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Amelia Torres",
                            Password = "Pass@123",
                            PhoneNumber = "7896541214",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 25,
                            Address = "1616 Cherry St, Madison, WI",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1122),
                            Email = "benjamin.ramirez@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Benjamin Ramirez",
                            Password = "Pass@123",
                            PhoneNumber = "7896541215",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 26,
                            Address = "1717 Chestnut Ave, Omaha, NE",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1124),
                            Email = "evelyn.cox@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Evelyn Cox",
                            Password = "Pass@123",
                            PhoneNumber = "7896541216",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 27,
                            Address = "1818 Beechwood Dr, Salt Lake City, UT",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1125),
                            Email = "logan.ward@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Logan Ward",
                            Password = "Pass@123",
                            PhoneNumber = "7896541217",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 28,
                            Address = "1919 Poplar Pl, Kansas City, MO",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1127),
                            Email = "harper.bailey@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Harper Bailey",
                            Password = "Pass@123",
                            PhoneNumber = "7896541218",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 29,
                            Address = "2020 Olive St, Des Moines, IA",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1128),
                            Email = "sebastian.bell@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Sebastian Bell",
                            Password = "Pass@123",
                            PhoneNumber = "7896541219",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 30,
                            Address = "2121 Dogwood Blvd, Boise, ID",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1130),
                            Email = "ella.cooper@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Ella Cooper",
                            Password = "Pass@123",
                            PhoneNumber = "7896541220",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 31,
                            Address = "2222 Hemlock Way, Little Rock, AR",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1131),
                            Email = "jackson.murphy@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Jackson Murphy",
                            Password = "Pass@123",
                            PhoneNumber = "7896541221",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 32,
                            Address = "2323 Pine Needle Rd, Fargo, ND",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1133),
                            Email = "avery.howard@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Avery Howard",
                            Password = "Pass@123",
                            PhoneNumber = "7896541222",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 33,
                            Address = "2424 Ivy Ln, Billings, MT",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1135),
                            Email = "daniel.ward@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Daniel Ward",
                            Password = "Pass@123",
                            PhoneNumber = "7896541223",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 34,
                            Address = "2525 Orchid Dr, Anchorage, AK",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1137),
                            Email = "scarlett.flores@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Scarlett Flores",
                            Password = "Pass@123",
                            PhoneNumber = "7896541224",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 35,
                            Address = "2626 Tulip Ln, Cheyenne, WY",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1139),
                            Email = "matthew.ross@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Matthew Ross",
                            Password = "Pass@123",
                            PhoneNumber = "7896541225",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 36,
                            Address = "2727 Daisy St, Helena, MT",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1140),
                            Email = "luna.sanders@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Luna Sanders",
                            Password = "Pass@123",
                            PhoneNumber = "7896541226",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 37,
                            Address = "2828 Fern Rd, Bismarck, ND",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1142),
                            Email = "david.jenkins@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "David Jenkins",
                            Password = "Pass@123",
                            PhoneNumber = "7896541227",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 38,
                            Address = "2929 Maplewood Ct, Dover, DE",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1143),
                            Email = "chloe.rogers@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Chloe Rogers",
                            Password = "Pass@123",
                            PhoneNumber = "7896541228",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 39,
                            Address = "3030 Bluebell Rd, Jackson, MS",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1145),
                            Email = "joseph.bryant@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Joseph Bryant",
                            Password = "Pass@123",
                            PhoneNumber = "7896541229",
                            Role = "DeliveryPartner"
                        },
                        new
                        {
                            UserId = 40,
                            Address = "3131 Tulip Hill Dr, Montgomery, AL",
                            CreatedDate = new DateTime(2025, 4, 6, 18, 46, 51, 31, DateTimeKind.Local).AddTicks(1146),
                            Email = "grace.hunter@example.com",
                            IsActive = true,
                            IsAvailble = true,
                            IsDeleted = false,
                            Name = "Grace Hunter",
                            Password = "Pass@123",
                            PhoneNumber = "7896541230",
                            Role = "DeliveryPartner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
