// <auto-generated />
using System;
using AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Main St, New York, NY",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(954),
                            Email = "chetanmundlesd@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chetan Mundle",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Elm St, Los Angeles, CA",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(969),
                            Email = "alice.brown@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Alice Brown",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 Pine Ave, Chicago, IL",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(970),
                            Email = "michael.smith@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Michael Smith",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "321 Oak St, Houston, TX",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(971),
                            Email = "emma.davis@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emma Davis",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "654 Maple Rd, Phoenix, AZ",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(972),
                            Email = "robert.wilson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Robert Wilson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 6,
                            Address = "987 Birch Blvd, Philadelphia, PA",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(976),
                            Email = "sophia.miller@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sophia Miller",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 7,
                            Address = "246 Cedar St, San Antonio, TX",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(977),
                            Email = "william.johnson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "William Johnson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 8,
                            Address = "135 Spruce Dr, San Diego, CA",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(978),
                            Email = "olivia.martinez@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Olivia Martinez",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 9,
                            Address = "753 Aspen Way, Dallas, TX",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(979),
                            Email = "james.anderson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "James Anderson",
                            Password = "Pass@123"
                        },
                        new
                        {
                            UserId = 10,
                            Address = "852 Redwood Ct, San Jose, CA",
                            CreatedDate = new DateTime(2025, 4, 1, 17, 21, 57, 777, DateTimeKind.Local).AddTicks(981),
                            Email = "isabella.thompson@example.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Isabella Thompson",
                            Password = "Pass@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
