// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantService.Data;

#nullable disable

namespace RestaurantService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250331161604_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantService.Entities.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 46, 3, 192, DateTimeKind.Local).AddTicks(799),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gulab Jamun",
                            Price = 100m,
                            RestaurantId = 1
                        },
                        new
                        {
                            MenuItemId = 2,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 46, 3, 192, DateTimeKind.Local).AddTicks(839),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samosa",
                            Price = 50m,
                            RestaurantId = 1
                        },
                        new
                        {
                            MenuItemId = 3,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 46, 3, 192, DateTimeKind.Local).AddTicks(867),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kachori",
                            Price = 50m,
                            RestaurantId = 1
                        });
                });

            modelBuilder.Entity("RestaurantService.Entities.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 46, 3, 192, DateTimeKind.Local).AddTicks(563),
                            IsActive = true,
                            IsDeleted = false,
                            RestaurantName = "Arav Dhaba"
                        });
                });

            modelBuilder.Entity("RestaurantService.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantService.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
