// <auto-generated />
using System;
using DeliveryService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250331161545_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliveryService.Entities.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DeliveryService.Entities.DeliveryPerson", b =>
                {
                    b.Property<int>("DeliveryPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryPersonId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryPersonId");

                    b.ToTable("DeliveryPersons");

                    b.HasData(
                        new
                        {
                            DeliveryPersonId = 1,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 45, 44, 885, DateTimeKind.Local).AddTicks(5764),
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "John M",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            DeliveryPersonId = 2,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 45, 44, 885, DateTimeKind.Local).AddTicks(5820),
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Melon ",
                            PhoneNumber = "2342356743"
                        },
                        new
                        {
                            DeliveryPersonId = 3,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 45, 44, 885, DateTimeKind.Local).AddTicks(5845),
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Keloni S T ",
                            PhoneNumber = "7684635238"
                        },
                        new
                        {
                            DeliveryPersonId = 4,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 45, 44, 885, DateTimeKind.Local).AddTicks(5866),
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Mr. R L",
                            PhoneNumber = "0983727843"
                        },
                        new
                        {
                            DeliveryPersonId = 5,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 45, 44, 885, DateTimeKind.Local).AddTicks(5888),
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Steno Dev",
                            PhoneNumber = "8378394384"
                        },
                        new
                        {
                            DeliveryPersonId = 6,
                            CreatedDate = new DateTime(2025, 3, 31, 21, 45, 44, 885, DateTimeKind.Local).AddTicks(5914),
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "John M",
                            PhoneNumber = "1234567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
